namespace IMS
{
    partial class frm_home
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frm_home));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges16 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.panel2 = new System.Windows.Forms.Panel();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_usermanagement = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_logout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_endofaday = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_inventory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_categories = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btn_dashboard = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel4 = new System.Windows.Forms.Panel();
            this.pnl_body = new System.Windows.Forms.Panel();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = true;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = this.panel2;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.White;
            this.panel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel2.Location = new System.Drawing.Point(200, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(824, 50);
            this.panel2.TabIndex = 1;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.bunifuButton1);
            this.panel1.Controls.Add(this.btn_usermanagement);
            this.panel1.Controls.Add(this.btn_logout);
            this.panel1.Controls.Add(this.btn_endofaday);
            this.panel1.Controls.Add(this.btn_inventory);
            this.panel1.Controls.Add(this.bunifuButton3);
            this.panel1.Controls.Add(this.btn_categories);
            this.panel1.Controls.Add(this.btn_dashboard);
            this.panel1.Controls.Add(this.panel4);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(200, 600);
            this.panel1.TabIndex = 0;
            this.panel1.Paint += new System.Windows.Forms.PaintEventHandler(this.panel1_Paint);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Inventory";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges9;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(165)))), ((int)(((byte)(166)))));
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.White;
            this.bunifuButton1.IdleBorderRadius = 5;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton1.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.IdleIconLeftImage")));
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(4, 270);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 5;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.bunifuButton1.onHoverState.BorderRadius = 5;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(224)))), ((int)(((byte)(161)))));
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.BorderRadius = 5;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(165)))), ((int)(((byte)(166)))));
            this.bunifuButton1.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.OnIdleState.IconLeftImage")));
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 5;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(224)))), ((int)(((byte)(161)))));
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(191, 39);
            this.bunifuButton1.TabIndex = 7;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(35, 0, 0, 0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // btn_usermanagement
            // 
            this.btn_usermanagement.AllowAnimations = true;
            this.btn_usermanagement.AllowMouseEffects = true;
            this.btn_usermanagement.AllowToggling = false;
            this.btn_usermanagement.AnimationSpeed = 200;
            this.btn_usermanagement.AutoGenerateColors = false;
            this.btn_usermanagement.AutoRoundBorders = false;
            this.btn_usermanagement.AutoSizeLeftIcon = true;
            this.btn_usermanagement.AutoSizeRightIcon = true;
            this.btn_usermanagement.BackColor = System.Drawing.Color.Transparent;
            this.btn_usermanagement.BackColor1 = System.Drawing.Color.White;
            this.btn_usermanagement.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_usermanagement.BackgroundImage")));
            this.btn_usermanagement.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_usermanagement.ButtonText = "User Management";
            this.btn_usermanagement.ButtonTextMarginLeft = 0;
            this.btn_usermanagement.ColorContrastOnClick = 45;
            this.btn_usermanagement.ColorContrastOnHover = 45;
            this.btn_usermanagement.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btn_usermanagement.CustomizableEdges = borderEdges10;
            this.btn_usermanagement.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_usermanagement.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_usermanagement.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_usermanagement.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_usermanagement.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_usermanagement.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_usermanagement.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(165)))), ((int)(((byte)(166)))));
            this.btn_usermanagement.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_usermanagement.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_usermanagement.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_usermanagement.IconMarginLeft = 11;
            this.btn_usermanagement.IconPadding = 10;
            this.btn_usermanagement.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_usermanagement.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_usermanagement.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_usermanagement.IconSize = 25;
            this.btn_usermanagement.IdleBorderColor = System.Drawing.Color.White;
            this.btn_usermanagement.IdleBorderRadius = 5;
            this.btn_usermanagement.IdleBorderThickness = 1;
            this.btn_usermanagement.IdleFillColor = System.Drawing.Color.White;
            this.btn_usermanagement.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_usermanagement.IdleIconLeftImage")));
            this.btn_usermanagement.IdleIconRightImage = null;
            this.btn_usermanagement.IndicateFocus = false;
            this.btn_usermanagement.Location = new System.Drawing.Point(4, 315);
            this.btn_usermanagement.Name = "btn_usermanagement";
            this.btn_usermanagement.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_usermanagement.OnDisabledState.BorderRadius = 5;
            this.btn_usermanagement.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_usermanagement.OnDisabledState.BorderThickness = 1;
            this.btn_usermanagement.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_usermanagement.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_usermanagement.OnDisabledState.IconLeftImage = null;
            this.btn_usermanagement.OnDisabledState.IconRightImage = null;
            this.btn_usermanagement.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_usermanagement.onHoverState.BorderRadius = 5;
            this.btn_usermanagement.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_usermanagement.onHoverState.BorderThickness = 1;
            this.btn_usermanagement.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_usermanagement.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(224)))), ((int)(((byte)(161)))));
            this.btn_usermanagement.onHoverState.IconLeftImage = null;
            this.btn_usermanagement.onHoverState.IconRightImage = null;
            this.btn_usermanagement.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_usermanagement.OnIdleState.BorderRadius = 5;
            this.btn_usermanagement.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_usermanagement.OnIdleState.BorderThickness = 1;
            this.btn_usermanagement.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_usermanagement.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(165)))), ((int)(((byte)(166)))));
            this.btn_usermanagement.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_usermanagement.OnIdleState.IconLeftImage")));
            this.btn_usermanagement.OnIdleState.IconRightImage = null;
            this.btn_usermanagement.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_usermanagement.OnPressedState.BorderRadius = 5;
            this.btn_usermanagement.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_usermanagement.OnPressedState.BorderThickness = 1;
            this.btn_usermanagement.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_usermanagement.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(224)))), ((int)(((byte)(161)))));
            this.btn_usermanagement.OnPressedState.IconLeftImage = null;
            this.btn_usermanagement.OnPressedState.IconRightImage = null;
            this.btn_usermanagement.Size = new System.Drawing.Size(191, 39);
            this.btn_usermanagement.TabIndex = 6;
            this.btn_usermanagement.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_usermanagement.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_usermanagement.TextMarginLeft = 0;
            this.btn_usermanagement.TextPadding = new System.Windows.Forms.Padding(35, 0, 0, 0);
            this.btn_usermanagement.UseDefaultRadiusAndThickness = true;
            this.btn_usermanagement.Click += new System.EventHandler(this.btn_usermanagement_Click);
            // 
            // btn_logout
            // 
            this.btn_logout.AllowAnimations = true;
            this.btn_logout.AllowMouseEffects = true;
            this.btn_logout.AllowToggling = false;
            this.btn_logout.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.btn_logout.AnimationSpeed = 200;
            this.btn_logout.AutoGenerateColors = false;
            this.btn_logout.AutoRoundBorders = false;
            this.btn_logout.AutoSizeLeftIcon = true;
            this.btn_logout.AutoSizeRightIcon = true;
            this.btn_logout.BackColor = System.Drawing.Color.Transparent;
            this.btn_logout.BackColor1 = System.Drawing.Color.White;
            this.btn_logout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_logout.BackgroundImage")));
            this.btn_logout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_logout.ButtonText = "Logout";
            this.btn_logout.ButtonTextMarginLeft = 0;
            this.btn_logout.ColorContrastOnClick = 45;
            this.btn_logout.ColorContrastOnHover = 45;
            this.btn_logout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btn_logout.CustomizableEdges = borderEdges11;
            this.btn_logout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_logout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_logout.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_logout.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_logout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_logout.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_logout.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.btn_logout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_logout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_logout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_logout.IconMarginLeft = 11;
            this.btn_logout.IconPadding = 10;
            this.btn_logout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_logout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_logout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_logout.IconSize = 25;
            this.btn_logout.IdleBorderColor = System.Drawing.Color.White;
            this.btn_logout.IdleBorderRadius = 5;
            this.btn_logout.IdleBorderThickness = 1;
            this.btn_logout.IdleFillColor = System.Drawing.Color.White;
            this.btn_logout.IdleIconLeftImage = null;
            this.btn_logout.IdleIconRightImage = null;
            this.btn_logout.IndicateFocus = false;
            this.btn_logout.Location = new System.Drawing.Point(4, 552);
            this.btn_logout.Name = "btn_logout";
            this.btn_logout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_logout.OnDisabledState.BorderRadius = 5;
            this.btn_logout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_logout.OnDisabledState.BorderThickness = 1;
            this.btn_logout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_logout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_logout.OnDisabledState.IconLeftImage = null;
            this.btn_logout.OnDisabledState.IconRightImage = null;
            this.btn_logout.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_logout.onHoverState.BorderRadius = 5;
            this.btn_logout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_logout.onHoverState.BorderThickness = 1;
            this.btn_logout.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btn_logout.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btn_logout.onHoverState.IconLeftImage = null;
            this.btn_logout.onHoverState.IconRightImage = null;
            this.btn_logout.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_logout.OnIdleState.BorderRadius = 5;
            this.btn_logout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_logout.OnIdleState.BorderThickness = 1;
            this.btn_logout.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_logout.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(44)))), ((int)(((byte)(62)))), ((int)(((byte)(80)))));
            this.btn_logout.OnIdleState.IconLeftImage = null;
            this.btn_logout.OnIdleState.IconRightImage = null;
            this.btn_logout.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_logout.OnPressedState.BorderRadius = 5;
            this.btn_logout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_logout.OnPressedState.BorderThickness = 1;
            this.btn_logout.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btn_logout.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_logout.OnPressedState.IconLeftImage = null;
            this.btn_logout.OnPressedState.IconRightImage = null;
            this.btn_logout.Size = new System.Drawing.Size(191, 39);
            this.btn_logout.TabIndex = 5;
            this.btn_logout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btn_logout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_logout.TextMarginLeft = 0;
            this.btn_logout.TextPadding = new System.Windows.Forms.Padding(0);
            this.btn_logout.UseDefaultRadiusAndThickness = true;
            // 
            // btn_endofaday
            // 
            this.btn_endofaday.AllowAnimations = true;
            this.btn_endofaday.AllowMouseEffects = true;
            this.btn_endofaday.AllowToggling = false;
            this.btn_endofaday.AnimationSpeed = 200;
            this.btn_endofaday.AutoGenerateColors = false;
            this.btn_endofaday.AutoRoundBorders = false;
            this.btn_endofaday.AutoSizeLeftIcon = true;
            this.btn_endofaday.AutoSizeRightIcon = true;
            this.btn_endofaday.BackColor = System.Drawing.Color.Transparent;
            this.btn_endofaday.BackColor1 = System.Drawing.Color.White;
            this.btn_endofaday.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_endofaday.BackgroundImage")));
            this.btn_endofaday.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_endofaday.ButtonText = "End of a Day";
            this.btn_endofaday.ButtonTextMarginLeft = 0;
            this.btn_endofaday.ColorContrastOnClick = 45;
            this.btn_endofaday.ColorContrastOnHover = 45;
            this.btn_endofaday.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btn_endofaday.CustomizableEdges = borderEdges12;
            this.btn_endofaday.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_endofaday.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_endofaday.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_endofaday.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_endofaday.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_endofaday.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_endofaday.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(165)))), ((int)(((byte)(166)))));
            this.btn_endofaday.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_endofaday.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_endofaday.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_endofaday.IconMarginLeft = 11;
            this.btn_endofaday.IconPadding = 10;
            this.btn_endofaday.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_endofaday.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_endofaday.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_endofaday.IconSize = 25;
            this.btn_endofaday.IdleBorderColor = System.Drawing.Color.White;
            this.btn_endofaday.IdleBorderRadius = 5;
            this.btn_endofaday.IdleBorderThickness = 1;
            this.btn_endofaday.IdleFillColor = System.Drawing.Color.White;
            this.btn_endofaday.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_endofaday.IdleIconLeftImage")));
            this.btn_endofaday.IdleIconRightImage = null;
            this.btn_endofaday.IndicateFocus = false;
            this.btn_endofaday.Location = new System.Drawing.Point(4, 360);
            this.btn_endofaday.Name = "btn_endofaday";
            this.btn_endofaday.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_endofaday.OnDisabledState.BorderRadius = 5;
            this.btn_endofaday.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_endofaday.OnDisabledState.BorderThickness = 1;
            this.btn_endofaday.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_endofaday.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_endofaday.OnDisabledState.IconLeftImage = null;
            this.btn_endofaday.OnDisabledState.IconRightImage = null;
            this.btn_endofaday.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_endofaday.onHoverState.BorderRadius = 5;
            this.btn_endofaday.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_endofaday.onHoverState.BorderThickness = 1;
            this.btn_endofaday.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_endofaday.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(224)))), ((int)(((byte)(161)))));
            this.btn_endofaday.onHoverState.IconLeftImage = null;
            this.btn_endofaday.onHoverState.IconRightImage = null;
            this.btn_endofaday.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_endofaday.OnIdleState.BorderRadius = 5;
            this.btn_endofaday.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_endofaday.OnIdleState.BorderThickness = 1;
            this.btn_endofaday.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_endofaday.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(165)))), ((int)(((byte)(166)))));
            this.btn_endofaday.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_endofaday.OnIdleState.IconLeftImage")));
            this.btn_endofaday.OnIdleState.IconRightImage = null;
            this.btn_endofaday.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_endofaday.OnPressedState.BorderRadius = 5;
            this.btn_endofaday.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_endofaday.OnPressedState.BorderThickness = 1;
            this.btn_endofaday.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_endofaday.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btn_endofaday.OnPressedState.IconLeftImage = null;
            this.btn_endofaday.OnPressedState.IconRightImage = null;
            this.btn_endofaday.Size = new System.Drawing.Size(191, 39);
            this.btn_endofaday.TabIndex = 4;
            this.btn_endofaday.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_endofaday.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_endofaday.TextMarginLeft = 0;
            this.btn_endofaday.TextPadding = new System.Windows.Forms.Padding(35, 0, 0, 0);
            this.btn_endofaday.UseDefaultRadiusAndThickness = true;
            // 
            // btn_inventory
            // 
            this.btn_inventory.AllowAnimations = true;
            this.btn_inventory.AllowMouseEffects = true;
            this.btn_inventory.AllowToggling = false;
            this.btn_inventory.AnimationSpeed = 200;
            this.btn_inventory.AutoGenerateColors = false;
            this.btn_inventory.AutoRoundBorders = false;
            this.btn_inventory.AutoSizeLeftIcon = true;
            this.btn_inventory.AutoSizeRightIcon = true;
            this.btn_inventory.BackColor = System.Drawing.Color.Transparent;
            this.btn_inventory.BackColor1 = System.Drawing.Color.White;
            this.btn_inventory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_inventory.BackgroundImage")));
            this.btn_inventory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory.ButtonText = "Inventory";
            this.btn_inventory.ButtonTextMarginLeft = 0;
            this.btn_inventory.ColorContrastOnClick = 45;
            this.btn_inventory.ColorContrastOnHover = 45;
            this.btn_inventory.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.btn_inventory.CustomizableEdges = borderEdges13;
            this.btn_inventory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_inventory.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_inventory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_inventory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_inventory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_inventory.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_inventory.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(165)))), ((int)(((byte)(166)))));
            this.btn_inventory.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_inventory.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_inventory.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_inventory.IconMarginLeft = 11;
            this.btn_inventory.IconPadding = 10;
            this.btn_inventory.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_inventory.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_inventory.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_inventory.IconSize = 25;
            this.btn_inventory.IdleBorderColor = System.Drawing.Color.White;
            this.btn_inventory.IdleBorderRadius = 5;
            this.btn_inventory.IdleBorderThickness = 1;
            this.btn_inventory.IdleFillColor = System.Drawing.Color.White;
            this.btn_inventory.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_inventory.IdleIconLeftImage")));
            this.btn_inventory.IdleIconRightImage = null;
            this.btn_inventory.IndicateFocus = false;
            this.btn_inventory.Location = new System.Drawing.Point(4, 225);
            this.btn_inventory.Name = "btn_inventory";
            this.btn_inventory.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_inventory.OnDisabledState.BorderRadius = 5;
            this.btn_inventory.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory.OnDisabledState.BorderThickness = 1;
            this.btn_inventory.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_inventory.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_inventory.OnDisabledState.IconLeftImage = null;
            this.btn_inventory.OnDisabledState.IconRightImage = null;
            this.btn_inventory.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_inventory.onHoverState.BorderRadius = 5;
            this.btn_inventory.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory.onHoverState.BorderThickness = 1;
            this.btn_inventory.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_inventory.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(224)))), ((int)(((byte)(161)))));
            this.btn_inventory.onHoverState.IconLeftImage = null;
            this.btn_inventory.onHoverState.IconRightImage = null;
            this.btn_inventory.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_inventory.OnIdleState.BorderRadius = 5;
            this.btn_inventory.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory.OnIdleState.BorderThickness = 1;
            this.btn_inventory.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_inventory.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(165)))), ((int)(((byte)(166)))));
            this.btn_inventory.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_inventory.OnIdleState.IconLeftImage")));
            this.btn_inventory.OnIdleState.IconRightImage = null;
            this.btn_inventory.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_inventory.OnPressedState.BorderRadius = 5;
            this.btn_inventory.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_inventory.OnPressedState.BorderThickness = 1;
            this.btn_inventory.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_inventory.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(224)))), ((int)(((byte)(161)))));
            this.btn_inventory.OnPressedState.IconLeftImage = null;
            this.btn_inventory.OnPressedState.IconRightImage = null;
            this.btn_inventory.Size = new System.Drawing.Size(191, 39);
            this.btn_inventory.TabIndex = 3;
            this.btn_inventory.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_inventory.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_inventory.TextMarginLeft = 0;
            this.btn_inventory.TextPadding = new System.Windows.Forms.Padding(35, 0, 0, 0);
            this.btn_inventory.UseDefaultRadiusAndThickness = true;
            this.btn_inventory.Click += new System.EventHandler(this.btn_inventory_Click);
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowAnimations = true;
            this.bunifuButton3.AllowMouseEffects = true;
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoRoundBorders = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "Products";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges14.BottomLeft = true;
            borderEdges14.BottomRight = true;
            borderEdges14.TopLeft = true;
            borderEdges14.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges14;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(165)))), ((int)(((byte)(166)))));
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.White;
            this.bunifuButton3.IdleBorderRadius = 5;
            this.bunifuButton3.IdleBorderThickness = 1;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton3.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.IdleIconLeftImage")));
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(4, 180);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.OnDisabledState.BorderRadius = 5;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 1;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.bunifuButton3.onHoverState.BorderRadius = 5;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(224)))), ((int)(((byte)(161)))));
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.bunifuButton3.OnIdleState.BorderRadius = 5;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(165)))), ((int)(((byte)(166)))));
            this.bunifuButton3.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.OnIdleState.IconLeftImage")));
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 5;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(224)))), ((int)(((byte)(161)))));
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(191, 39);
            this.bunifuButton3.TabIndex = 2;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(35, 0, 0, 0);
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            this.bunifuButton3.Click += new System.EventHandler(this.bunifuButton3_Click);
            // 
            // btn_categories
            // 
            this.btn_categories.AllowAnimations = true;
            this.btn_categories.AllowMouseEffects = true;
            this.btn_categories.AllowToggling = false;
            this.btn_categories.AnimationSpeed = 200;
            this.btn_categories.AutoGenerateColors = false;
            this.btn_categories.AutoRoundBorders = false;
            this.btn_categories.AutoSizeLeftIcon = true;
            this.btn_categories.AutoSizeRightIcon = true;
            this.btn_categories.BackColor = System.Drawing.Color.Transparent;
            this.btn_categories.BackColor1 = System.Drawing.Color.White;
            this.btn_categories.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_categories.BackgroundImage")));
            this.btn_categories.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_categories.ButtonText = "Category";
            this.btn_categories.ButtonTextMarginLeft = 0;
            this.btn_categories.ColorContrastOnClick = 45;
            this.btn_categories.ColorContrastOnHover = 45;
            this.btn_categories.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges15.BottomLeft = true;
            borderEdges15.BottomRight = true;
            borderEdges15.TopLeft = true;
            borderEdges15.TopRight = true;
            this.btn_categories.CustomizableEdges = borderEdges15;
            this.btn_categories.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_categories.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_categories.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_categories.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_categories.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_categories.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_categories.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(165)))), ((int)(((byte)(166)))));
            this.btn_categories.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_categories.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_categories.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_categories.IconMarginLeft = 11;
            this.btn_categories.IconPadding = 10;
            this.btn_categories.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_categories.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_categories.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_categories.IconSize = 25;
            this.btn_categories.IdleBorderColor = System.Drawing.Color.White;
            this.btn_categories.IdleBorderRadius = 5;
            this.btn_categories.IdleBorderThickness = 1;
            this.btn_categories.IdleFillColor = System.Drawing.Color.White;
            this.btn_categories.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_categories.IdleIconLeftImage")));
            this.btn_categories.IdleIconRightImage = null;
            this.btn_categories.IndicateFocus = false;
            this.btn_categories.Location = new System.Drawing.Point(4, 135);
            this.btn_categories.Name = "btn_categories";
            this.btn_categories.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_categories.OnDisabledState.BorderRadius = 5;
            this.btn_categories.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_categories.OnDisabledState.BorderThickness = 1;
            this.btn_categories.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_categories.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_categories.OnDisabledState.IconLeftImage = null;
            this.btn_categories.OnDisabledState.IconRightImage = null;
            this.btn_categories.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_categories.onHoverState.BorderRadius = 5;
            this.btn_categories.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_categories.onHoverState.BorderThickness = 1;
            this.btn_categories.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_categories.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(224)))), ((int)(((byte)(161)))));
            this.btn_categories.onHoverState.IconLeftImage = null;
            this.btn_categories.onHoverState.IconRightImage = null;
            this.btn_categories.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_categories.OnIdleState.BorderRadius = 5;
            this.btn_categories.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_categories.OnIdleState.BorderThickness = 1;
            this.btn_categories.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_categories.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(165)))), ((int)(((byte)(166)))));
            this.btn_categories.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_categories.OnIdleState.IconLeftImage")));
            this.btn_categories.OnIdleState.IconRightImage = null;
            this.btn_categories.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_categories.OnPressedState.BorderRadius = 5;
            this.btn_categories.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_categories.OnPressedState.BorderThickness = 1;
            this.btn_categories.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_categories.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(224)))), ((int)(((byte)(161)))));
            this.btn_categories.OnPressedState.IconLeftImage = null;
            this.btn_categories.OnPressedState.IconRightImage = null;
            this.btn_categories.Size = new System.Drawing.Size(191, 39);
            this.btn_categories.TabIndex = 1;
            this.btn_categories.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_categories.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_categories.TextMarginLeft = 0;
            this.btn_categories.TextPadding = new System.Windows.Forms.Padding(35, 0, 0, 0);
            this.btn_categories.UseDefaultRadiusAndThickness = true;
            this.btn_categories.Click += new System.EventHandler(this.btn_categories_Click);
            // 
            // btn_dashboard
            // 
            this.btn_dashboard.AllowAnimations = true;
            this.btn_dashboard.AllowMouseEffects = true;
            this.btn_dashboard.AllowToggling = false;
            this.btn_dashboard.AnimationSpeed = 200;
            this.btn_dashboard.AutoGenerateColors = false;
            this.btn_dashboard.AutoRoundBorders = false;
            this.btn_dashboard.AutoSizeLeftIcon = true;
            this.btn_dashboard.AutoSizeRightIcon = true;
            this.btn_dashboard.BackColor = System.Drawing.Color.Transparent;
            this.btn_dashboard.BackColor1 = System.Drawing.Color.White;
            this.btn_dashboard.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btn_dashboard.BackgroundImage")));
            this.btn_dashboard.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_dashboard.ButtonText = "Dashboard";
            this.btn_dashboard.ButtonTextMarginLeft = 0;
            this.btn_dashboard.ColorContrastOnClick = 45;
            this.btn_dashboard.ColorContrastOnHover = 45;
            this.btn_dashboard.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges16.BottomLeft = true;
            borderEdges16.BottomRight = true;
            borderEdges16.TopLeft = true;
            borderEdges16.TopRight = true;
            this.btn_dashboard.CustomizableEdges = borderEdges16;
            this.btn_dashboard.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btn_dashboard.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_dashboard.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_dashboard.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_dashboard.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btn_dashboard.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btn_dashboard.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(165)))), ((int)(((byte)(166)))));
            this.btn_dashboard.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_dashboard.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btn_dashboard.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btn_dashboard.IconMarginLeft = 11;
            this.btn_dashboard.IconPadding = 10;
            this.btn_dashboard.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btn_dashboard.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btn_dashboard.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btn_dashboard.IconSize = 25;
            this.btn_dashboard.IdleBorderColor = System.Drawing.Color.White;
            this.btn_dashboard.IdleBorderRadius = 5;
            this.btn_dashboard.IdleBorderThickness = 1;
            this.btn_dashboard.IdleFillColor = System.Drawing.Color.White;
            this.btn_dashboard.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_dashboard.IdleIconLeftImage")));
            this.btn_dashboard.IdleIconRightImage = null;
            this.btn_dashboard.IndicateFocus = false;
            this.btn_dashboard.Location = new System.Drawing.Point(4, 90);
            this.btn_dashboard.Name = "btn_dashboard";
            this.btn_dashboard.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btn_dashboard.OnDisabledState.BorderRadius = 5;
            this.btn_dashboard.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_dashboard.OnDisabledState.BorderThickness = 1;
            this.btn_dashboard.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btn_dashboard.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btn_dashboard.OnDisabledState.IconLeftImage = null;
            this.btn_dashboard.OnDisabledState.IconRightImage = null;
            this.btn_dashboard.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(255)))), ((int)(((byte)(230)))));
            this.btn_dashboard.onHoverState.BorderRadius = 5;
            this.btn_dashboard.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_dashboard.onHoverState.BorderThickness = 1;
            this.btn_dashboard.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_dashboard.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(224)))), ((int)(((byte)(161)))));
            this.btn_dashboard.onHoverState.IconLeftImage = null;
            this.btn_dashboard.onHoverState.IconRightImage = null;
            this.btn_dashboard.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btn_dashboard.OnIdleState.BorderRadius = 5;
            this.btn_dashboard.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_dashboard.OnIdleState.BorderThickness = 1;
            this.btn_dashboard.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btn_dashboard.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(149)))), ((int)(((byte)(165)))), ((int)(((byte)(166)))));
            this.btn_dashboard.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btn_dashboard.OnIdleState.IconLeftImage")));
            this.btn_dashboard.OnIdleState.IconRightImage = null;
            this.btn_dashboard.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_dashboard.OnPressedState.BorderRadius = 5;
            this.btn_dashboard.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btn_dashboard.OnPressedState.BorderThickness = 1;
            this.btn_dashboard.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(230)))), ((int)(((byte)(237)))), ((int)(((byte)(207)))));
            this.btn_dashboard.OnPressedState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(208)))), ((int)(((byte)(224)))), ((int)(((byte)(161)))));
            this.btn_dashboard.OnPressedState.IconLeftImage = null;
            this.btn_dashboard.OnPressedState.IconRightImage = null;
            this.btn_dashboard.Size = new System.Drawing.Size(191, 39);
            this.btn_dashboard.TabIndex = 0;
            this.btn_dashboard.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btn_dashboard.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btn_dashboard.TextMarginLeft = 0;
            this.btn_dashboard.TextPadding = new System.Windows.Forms.Padding(35, 0, 0, 0);
            this.btn_dashboard.UseDefaultRadiusAndThickness = true;
            this.btn_dashboard.Click += new System.EventHandler(this.btn_dashboard_Click);
            // 
            // panel4
            // 
            this.panel4.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel4.Location = new System.Drawing.Point(0, 0);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(200, 50);
            this.panel4.TabIndex = 0;
            // 
            // pnl_body
            // 
            this.pnl_body.BackColor = System.Drawing.Color.Red;
            this.pnl_body.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnl_body.Location = new System.Drawing.Point(200, 50);
            this.pnl_body.Name = "pnl_body";
            this.pnl_body.Size = new System.Drawing.Size(824, 550);
            this.pnl_body.TabIndex = 2;
            this.pnl_body.Paint += new System.Windows.Forms.PaintEventHandler(this.pnl_body_Paint);
            // 
            // frm_home
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Inherit;
            this.ClientSize = new System.Drawing.Size(1024, 600);
            this.Controls.Add(this.pnl_body);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "frm_home";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "frm_home";
            this.ResizeBegin += new System.EventHandler(this.frm_home_ResizeBegin);
            this.Resize += new System.EventHandler(this.frm_home_Resize);
            this.panel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel pnl_body;
        private System.Windows.Forms.Panel panel4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_endofaday;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_inventory;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_categories;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_dashboard;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_logout;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btn_usermanagement;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
    }
}